---
title: "Survey Validation"
subtitle: "Autism Spectrum Disorder Therapy in India"
author: "Ajay Krishnakumar, Amie Thomas, Yang Xiao, Yuchen Huang"
date: "2023-10-31"
output: html_document
---

#Summary

-high level overview of the main points of the paper with minimal details. Includes key findings and recommendations

#Introduction

-brief description of projects objectives and context

-research questions/ goals of analysis defined

#Methodology

-details of data preprocessing steps (data cleaning or transformations)

-statistical methods and techniques used in analysis

#Data description

-summary of data with descriptive statistics, data distributions, data visualizations (tables, charts, graphs

-discuss missing data and how it was handled

#Statistical Analysis with Visuals

-main results of the analysis with relevant visuals

-interpretation of the results in plain language that can be understood by our nontechnical reader Suma

#Overall Findings

Regrettably, we cannot say with any degree of certainty whether or not the data collected and the survey which was used to collect them satisfy conditions of construct validity or reliability from a statistical standpoint. This is on the strength of the following facts:

1) That the survey questions of interest do not on a prima facie basis seem to be asking the same thing. The questions bundled under 'quality' for instance ask a wide variety of things from the respondents. Any measure of reliability for questions that are so obviously different would not itself be reliable. 

2) The loadings on the principal component analysis we conducted and the associated eigenvalues indicate that any measure of reliability would not be reliable or stable (Yurdugul 2008). Further the small loadings and their distribution across separate 'components' would seem to be indicative of the fact that the client's grouping of variables is not valid. Beyond saying that the grouping is not valid, when confronted with individual questions, treated as variables, and considering the fact that the data needs to be split into two groups along the lines of those who attended Speech Language Therapy and those who didn't, the sample size together with the number of survey items for each group leads any statement about surey validity to be inconclusive. 

Any statements as to the validity or reliability of the survey must instead stem from the methodology of the survey, the way it was circulated, the people that might have overseen it, the standards for the field and from peers of the researcher, since statistically no conclusion as to these metrics can be definitively reached. 

There are however, ways in which the client can make data from the survey more suitable for analysis and make any conclusions more sound. These are laid out below. 

#Recommendations

1) It was mentioned by the client, in passing, that certain parts of the data(such as the days per week that children attended Speech language Therapy) might have been coded differently in the data than the way they were collected. It might be best, especially in this case but also generally, to avoid sumamries and codings until the analysis is done and then to explicitly indicate where this is so. 

2) As we've said above, the groupings of 'quality' and 'access' are not necessarily correct across either of the Speech Language and No Speech Languge groups. It might be best to address these questions as separate variables measuring separate things, albeit slightly related. 

3) <Recommendations made on the basis of

#Conclusions

-key takeaways from analysis

-reiterate importance of findings and recommendations

#References

-yall know what references are

#Glossary

-technical terms/ jargon used in report with definitions so that our non technical reader Suma can better understand.
